export const ADD_USER = "ADD_USER";

export const UPDATE_USERS="UPDATE_USERS";
export const UPDATE_TOTAL_NUMBER_OF_USERS="UPDATE_TOTAL_NUMBER_OF_USERS"
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const DELETE_USER = "DELETE_USER";

export const SET_CURRENT_USER_NAME="SET_CURRENT_USER_NAME"
export const SET_CURRENT_USER_EMAIL="SET_CURRENT_USER_EMAIL"
export const SET_CURRENT_USER_TEAM="SET_CURRENT_USER_EMAIL"