// User

export const ADD_USER = "ADD_USER";
export const UPDATE_USERS="UPDATE_USERS";
export const UPDATE_TOTAL_NUMBER_OF_USERS="UPDATE_TOTAL_NUMBER_OF_USERS"
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const DELETE_USER = "DELETE_USER";

// Team

export const ADD_TEAM = "ADD_TEAM";
export const UPDATE_TEAM="UPDATE_TEAM";

export const UPDATE_CURRENT_TEAM = "UPDATE_CURRENT_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";

// permissions
export const UPDATE_PERMISSION_TRANSLATIONS="UPDATE_PERMISSION_TRANSLATIONS"
export const UPDATE_TEAM_LIST_ITEMS="UPDATE_TEAM_LIST_ITEMS"

export const UPDATE_USER_LIST_ITEMS="UPDATE_USER_LIST_ITEMS"
